[package]
name = "bevy_replicate"
version = "0.1.0"
authors = ["Valaphee <iam@valaphee.com>"]
description = "Replication for Bevy"
repository = "https://github.com/valaphee/bevy_replicate.git"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bevy = { path = "../bevy", default-features = false }
quinn = "0.10.2"
rustls = "0.21.0"
rcgen = "0.12.1"
tokio = { version = "1.28.1", features = ["full"] }

[workspace]
resolver = "2"
members = ["example"]

