[package]
name = "bevy_replicate"
version = "0.1.0"
authors = ["Valaphee <iam@valaphee.com>"]
description = "Replication for Bevy"
repository = "https://github.com/valaphee/bevy_replicate.git"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = ["bevy_winit", "bevy_pbr", "ktx2", "zstd", "tonemapping_luts", "mp3"] }

